### ISSUE TITLE
/bin/sh: context: command not found

### ISSUE THREAD

**Issue by bbgky** [mszep/pandoc_resume#16]
Hi,
I am using mac and just installed Standalone ConText  by following http://wiki.contextgarden.net/Mac_Installation#Standalone_ConTeXt

but when i run `make`, it gave `/bin/sh: context: command not found`.
So the pdf version is not showing up.

**Comment by mszep** [comment]
Can you run context from the command line, i.e. when you type `context` in a terminal, does it say `command not found` or something else?

You may need to manually add context to your `$PATH` variable.

**Comment by bbgky** [comment]
Oh Tahnks! Indeed, the path of context is not configured properly. 
It is working now.
