### ISSUE TITLE
Is it possible to get Font Awesome or images into the PDF?

### ISSUE THREAD

**Issue by systemovich** [mszep/pandoc_resume#20]
I can get fonts and images into the HTML, but not the PDF.

**Comment by mszep** [comment]
Hi,

Both issues are related to ConTeXt, the engine that pandoc_resume uses to generate the pdf.

Images should work I think if they are included in the working directory, and are of one of the formats supported by ConTeXt (note: .gif is not one of them). See here for more information: http://wiki.contextgarden.net/Using_Graphics

Re: fonts, I'm not sure how to add fonts in ConTeXt as I've never had to, but you should be able to find more information here: http://wiki.contextgarden.net/Fonts

Let me know if this helps in resolving your issue!

**Comment by systemovich** [comment]
@mszep thanks. I decided to go with Latex and moderncv.
