### ISSUE TITLE
Building pdf on linux fails with texmf/lua error

### ISSUE THREAD

**Issue by cbcoutinho** [mszep/pandoc_resume#26]
I just cloned the repository and attempted to build the example resume into a pdf. I'm on openSUSE Leap 42.2, and have installed texlive, context, and pandoc as specified in the README. I'm pretty sure I'm missing some dependency, or texlive/texmf is not configured correctly, but I'm not a TeX expert so I'm sort of at a loss what the error message below means.

The `make html` command works fine, this is primarily and tex/pdf issue as far as I can tell.

Running the make command fails as follows:

```
$ make pdf
pandoc --standalone --template style_chmduquesne.tex \
--from markdown --to context \
-V papersize=A4 \
-o resume.tex resume.md; \
context resume.tex

mtxrun          | forcing cache reload
resolvers       | resolving | looking for 'texmfcnf.lua' on given path '/home/chris/texmf/web2c' from specification 'home:texmf/web2c'
resolvers       | resolving | looking for 'texmfcnf.lua' on weird path '/etc/texmf:/etc/texmf/web2c:/var/lib/texmf/web2c:$TEXMF/web2c' from specification '/etc/texmf:/etc/texmf/web2c:/var/lib/texmf/web2c:$TEXMF/web2c'
resolvers       | resolving |
resolvers       | resolving | warning: no lua configuration files found
resolvers       | resolving | no texmf paths are defined (using TEXMF)
resolvers       | resolving |
mtxrun          | the resolver databases are not present or outdated
resolvers       | resolving | using suffix based filetype 'scripts'
resolvers       | resolving | remembering file 'mtx-context.lua' using hash 'lua::mtx-context.lua'
resolvers       | resolving | using suffix based filetype 'scripts'
resolvers       | resolving | remembering file 'mtx-contexts.lua' using hash 'lua::mtx-contexts.lua'
resolvers       | resolving | remembered file 'mtx-context.lua'
resolvers       | resolving | using suffix based filetype 'scripts'
resolvers       | resolving | remembering file 'mtx-t-context.lua' using hash 'lua::mtx-t-context.lua'
resolvers       | resolving | using suffix based filetype 'scripts'
resolvers       | resolving | remembering file 'mtx-t-contexts.lua' using hash 'lua::mtx-t-contexts.lua'
resolvers       | resolving | remembered file 'mtx-t-context.lua'
resolvers       | resolving | using suffix based filetype 'scripts'
resolvers       | resolving | remembering file 'context.lua' using hash 'lua::context.lua'
mtxrun          | unknown script 'context.lua' or 'mtx-context.lua'
Makefile:5: recipe for target 'resume.pdf' failed
make: *** [resume.pdf] Error 1
```

**Comment by mszep** [comment]
(Sorry for the delayed response)

That's a strange error, and it's probably something like you suggest, a configuration issue. I presume you installed both context and texlive using SuSe's package manager? Maybe you can try compiling some simple documents with luatex and pdftex, that could give more clues?

**Comment by shashankpr** [comment]
@cbcoutinho Hi ! I too got the same error when I ran `make` for the first time. 
If you see the `context_resume.log` in the output folder, it might say something like *unknown script 'context.lua' or 'mtx-context.lua'*. Check for the following two things to resolve this:
- Check if `context's` *texmf* is added in your PATH variable in bash profile. 
(The path to *texmf* for me looks like this : "/Users/shashank/context/tex/texmf-osx-64/bin")
- If the above is done then try running: `mtxrun --generate`

Doing these two steps worked for me.

**Comment by cbcoutinho** [comment]
Thanks for the tip! Indeed, running `mtxrun --generate` in the project directory fixed the problem and now building the pdf works
