### ISSUE TITLE
Syntax for align right

### ISSUE THREAD

**Issue by louisabraham** [mszep/pandoc_resume#27]
Hi,

I am very happy with pandoc_resume, and did my own version (https://github.com/louisabraham/my_markdown_resume).

Not really an issue, but in your blog post https://mszep.github.io/pandoc_resume/, you used this syntax that works perfectly:

    -------------------     ----------------------------
    1 MyAddress                        email@example.com
    MyTown 1000                          @twitter_handle
    MyCountry                           1800 my-phone-nr
    -------------------     ----------------------------

However, sometimes it doesn't work quite right (does something like a center right and not a right align), depends on the number of spaces / tabs / dashes I put.

Could you please give a reference for this construction?

**Comment by mszep** [comment]
The interpreting of cell alignments is done by pandoc, and the syntax can be viewed here: https://pandoc.org/MANUAL.html#tables

Let me know if this helps you fix your issue; if not, please feel free to post a snippet here that shows the broken behavior so I can try to reproduce.

**Comment by louisabraham** [comment]
Oh thank you for the reference, I never understood the column alignment before now!

Again, thanks for your template!
