### ISSUE TITLE
Help for new user of ConTeXt

### ISSUE THREAD

**Issue by Aluriak** [mszep/pandoc_resume#29]
Hi !

This idea is awesome, i love it !
(and use it, too :) )

I had problems generating the pdf using ConTeXt, strangely equivalent to #25/#26. I fixed them by running `mtxrun --generate`, as suggested [here](https://tex.stackexchange.com/questions/53892/texlive-2011-context-problem). I do not really understand what it does, but it works. Maybe indicating this in the README could be helpful.

I'm on archlinux.

**Comment by mszep** [comment]
What version of archlinux are you on? Is it perhaps one where context is part of texlive, as mentioned in the stackoverflow link you posted?

My understanding is on modern systems, ConTeXt should be its own standalone package, not dependent on texlive. If this isn't the case, I'd be happy to add a "Troubleshooting" section in the README describing your workaround.

**Comment by Aluriak** [comment]
> What version of archlinux are you on?

The lastest

> Is it perhaps one where context is part of texlive

It is exactly how it is packaged on archlinux ; i do not know if there is any plan for the standalone packaging.

> I'd be happy to add a "Troubleshooting" section in the README describing your workaround.

I think its the best thing we can do, currently.

**Comment by mszep** [comment]
Fixed [here](https://github.com/mszep/pandoc_resume/commit/6101cd5406157e219b2e5a0bdb107eee09517d10), thanks for reporting!
