### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by nitrocode** [mszep/pandoc_resume#31]
I noticed that the generated HTML works well but is not mobile friendly. And now that most devices are mobile and developers always design mobile first, if bandwidth allows, it would be nice to see a mobile friendly version of this.

I'm not sure if that's a configuration in pandoc or with the CSS file. It seems possible as [pandoc-moderncv](https://github.com/barraq/pandoc-moderncv) has this functionality so it's definitely possible.

Thank you for this repo! Love generating my resume from markdown.

**Comment by mszep** [comment]
It would probably mainly be in the CSS. Unfortunately I don't have time to work on that right now, but if you'd like to contribute a change, I'm happy to look at it!

**Comment by mszep** [comment]
I've merged #32, so let me know if you have any other suggestions :-)
