### ISSUE TITLE
Pandoc now converts table to xtables instead of Tables

### ISSUE THREAD

**Issue by jdumas** [mszep/pandoc_resume#35]
Hi,

The latest release of [pandoc](https://github.com/jgm/pandoc/releases/tag/2.1.1) now converts tables to `xtables` in Context, which breaks the example you have on the webpage:

```
Johnny Coder
============

-------------------     ----------------------------
1 MyAddress                        email@example.com
MyTown 1000                          @twitter_handle
MyCountry                           1800 my-phone-nr
-------------------     ----------------------------
```

However, I am a newb with context, so I don't know how to set the table width to the width of the page, and suppress the table lines ... (`\setuptables[textwidth=max]` in the current code).

**Comment by jdumas** [comment]
Got it, you need to set up this option in the .tex preamble:

```
\setupxtable[frame=off,option={stretch,width}]
```

Hope this helps those with the same issue.

**Comment by mszep** [comment]
Cool, thanks for pointing that out; I'll add a fix when I get a chance :-)

**Comment by billywade** [comment]
Pull #38 fixed the problem for me
