### ISSUE TITLE
Github Issue Template

### ISSUE THREAD

**Issue by nitrocode** [mszep/pandoc_resume#40]
Source: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

It would be nice if there was a template that asked for `pandoc` and `context` versions and operating system and operating system version.

    pandoc --version
    context --version
    cat /etc/lsb-release

**Comment by mszep** [comment]
:+1: can add that when I get some time, or I'd be happy to merge it in if someone wants to sort that out...

**Comment by nitrocode** [comment]
@mszep I did this 3 weeks ago and forgot to create a PR :thinking:
