### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by nitrocode** [mszep/pandoc_resume#49]
Thank you @mszep for starting this project because it helped get me create multiple resumes, cover letters, interviews, which lead to multiple job offers, and finally a job!

I enjoyed adding my own contributions to it and hope it helps others. :smile:

**Comment by mszep** [comment]
Great to hear @nitrocode, and congrats on your new job! I had hoped this project might help someone in this way, but you're the first confirmed case :-)

And thank _you_ for your thoughtful contributions in other issues -- it's greatly appreciated!

**Comment by deronnax** [comment]
thank you also, @mszep
