### ISSUE TITLE
[WARNING] This document format requires a nonempty <title> element.

### ISSUE THREAD

**Issue by nitrocode** [mszep/pandoc_resume#53]
### Expected Behavior

No warning

### Actual Behavior

Shows warning

> [WARNING] This document format requires a nonempty <title> element.

### Steps to reproduce the behavior

    make

### Versions

pandoc: 2.5
context: 1.02
OS: OSX

**Comment by bpjohannessen** [comment]
I encountered this error on Windows 10 with pandoc 2.5 and context 1.02. On Linux and macOS I don't receive this error, so I guess this is an error in the installation..?
