### ISSUE TITLE
/bin/sh: mtxrun: not found (Docker on Ubuntu 20.04)

### ISSUE THREAD

**Issue by miarn** [mszep/pandoc_resume#83]
### Expected Behavior
On running `docker-compose up -d`, `resume.pdf` should be generated.

### Actual Behavior
No PDF is generated (.html and .tex are both created, apparently without error). `output/context_resume.log` shows the following:
````
cat output/context_resume.log
/bin/sh: mtxrun: not found
````

On further investigation, it seems that while pandoc is installed fine:
````
% docker run -it resume-make sh
/data # pandoc --version
pandoc 2.9
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
Default user data directory: /root/.local/share/pandoc or /root/.pandoc
````

ConTeXt is not:
````
/data # context --version
sh: context: not found
````

### Steps to reproduce the behavior
````
git clone https://github.com/mszep/pandoc_resume
docker-compose up -d
````

### Versions

Pandoc and ConTeXt versions as above.

OS is Ubuntu 20.04.3 LTS.

**Comment by jmpolom** [comment]
It looks like `mtxrun` is not included in the pandoc/latex container image.

**Comment by atsaloli** [comment]
I ran into this as well.
