### ISSUE TITLE
superscript

### ISSUE THREAD

**Issue by GuangchuangYu** [mszep/pandoc_resume#9]
Hi, I use your pandoc_resume. It's great.

I have a question of how to add superscript. I use latex $^*$ to implement this effect, but wondering is it possible to use a markdown syntax to achieve this?

Best wishes,
Guangchuang

**Comment by mszep** [comment]
Hi, sorry for the delay in responding, I've been too busy to follow github this summer.

Since pandoc_resume uses pandoc in the background, you can use the pandoc format for (sub/super)scripts: http://pandoc.org/README.html#superscripts-and-subscripts

Hope this helps!

**Comment by GuangchuangYu** [comment]
thanks.
